[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "HECTRE"
version = "0.0.1"
requires-python = ">=3.8"

[tool.pytest.ini_options]
minversion = "7.0"
testpaths = [
    "tests",
]
python_functions = "*should*"